# Generated by Django 2.2.3 on 2019-08-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.BigIntegerField(default=23),
            preserve_default=False,
        ),
    ]
