# Generated by Django 2.2.3 on 2019-08-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digs', '0002_expenses_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='categories',
            new_name='category',
        ),
    ]
